module JobpreferencesHelper
  def region_options_us_and_france
    Carmen::Country.all.select { |c| %w(US FR).include?(c.code) }.map { |r| [r.code, r.code] }
end

  def days
    days = ['London',
            'Aberdeen',
            'Aberdeenshire',
            'Amber Valley',
            'Angus',
            'Arun',
            'Ashfield',
            'Aylesbury Vale',
            'Barnsley',
            'Basildon',
            'Basingstoke and Deane',
            'Bassetlaw',
            'Bath &amp; North East Somerset',
            'Bedford',
            'Belfast',
            'Birmingham',
            'Blackburn',
            'Blackpool',
            'Bolton',
            'Bournemouth',
            'Bracknell Forest',
            'Bradford',
            'Braintree',
            'Breckland',
            'Bridgend',
            'Brighton',
            'Bristol',
            'Broadland',
            'Broxtowe',
            'Bury',
            'Caerphilly',
            'Calderdale',
            'Cambridge',
            'Canterbury',
            'Cardiff',
            'Carmarthenshire',
            'Charnwood',
            'Chelmsford',
            'Cheltenham',
            'Cherwell',
            'Chester',
            'Colchester',
            'Conway',
            'Coventry',
            'Crewe and Nantwich',
            'Dacorum',
            'Derby',
            'Doncaster',
            'Dover',
            'Dudley',
            'Dumfries and Galloway',
            'Dundee',
            'East Ayrshire',
            'East Devon',
            'East Dunbartonshire',
            'East Hampshire',
            'East Hertfordshire',
            'East Lindsey',
            'East Riding',
            'Eastleigh',
            'Edinburgh',
            'Elmbridge',
            'Epping Forest',
            'Erewash',
            'Exeter',
            'Falkirk',
            'Fife',
            'Flintshire',
            'Gateshead',
            'Gedling',
            'Glasgow',
            'Gloucester',
            'Guildford',
            'Gwynedd',
            'Halton',
            'Harrogate',
            'Havant and Waterloo',
            'Highland',
            'Horsham',
            'Huntingdonshire',
            'Ipswich',
            'Isle of Wight',
            'Kings Lynn',
            'Kingston-upon-Hull',
            'Kirklees',
            'Knowsley',
            'Lancaster',
            'Leeds',
            'Leicester',
            'Lisburn',
            'Liverpool',
            'Luton',
            'Macclesfield',
            'Maidstone',
            'Manchester',
            'Mid Bedfordshire',
            'Mid Sussex',
            'Middlesbrough',
            'Milton Keynes',
            'Neath Port Talbot',
            'New Forest',
            'Newbury',
            'Newcastle-under-Lyme',
            'Newcastle-upon-Tyne',
            'Newport',
            'North Ayrshire',
            'North East Lincolnshire',
            'North Hertfordshire',
            'North Lanarkshire',
            'North Lincolnshire',
            'North Somerset',
            'North Tyneside',
            'North Wiltshire',
            'Northampton',
            'Norwich',
            'Nottingham',
            'Nuneaton and Bedworth',
            'Oldham',
            'Oxford',
            'Pembrokeshire',
            'Perth and Kinross',
            'Peterborough',
            'Plymouth',
            'Poole',
            'Portsmouth',
            'Powys',
            'Preston',
            'Reading',
            'Redcar and Cleveland',
            'Reigate and Banstead',
            'Renfrewshire',
            'Rhondda, Cynon, Taff',
            'Rochdale',
            'Rochester-upon-Medway',
            'Rotherham',
            'Salford',
            'Salisbury',
            'Scarborough',
            'Sefton',
            'Sevenoaks',
            'Sheffield',
            'Slough',
            'Solihull',
            'South Ayrshire',
            'South Bedfordshire',
            'South Cambridgeshire',
            'South Gloucestershire',
            'South Kesteven',
            'South Lanarkshire',
            'South Oxfordshire',
            'South Somerset',
            'South Tyneside',
            'Southampton',
            'Southend-on-Sea',
            'St Albans',
            'St Helens',
            'Stafford',
            'Stockport',
            'Stockton-on-Tees',
            'Stoke-on-Trent',
            'Stratford-on-Avon',
            'Stroud',
            'Suffolk Coastal',
            'Sunderland',
            'Sandwell',
            'Swale',
            'Swansea',
            'Tameside',
            'Teignbridge',
            'Tendring',
            'Test Valley',
            'Thamesdown',
            'Thanet',
            'The Wrekin',
            'Thurrock',
            'Torbay',
            'Trafford',
            'Vale of Glamorgan',
            'Vale of White Horse',
            'Vale Royal',
            'Wakefield',
            'Walsall',
            'Warrington',
            'Warwick',
            'Waveney',
            'Waverley',
            'Wealden',
            'West Lancashire',
            'West Lothian',
            'West Wiltshire',
            'Wigan',
            'Windsor &amp; Maidenhead',
            'Wirral',
            'Wokingham',
            'Wolverhampton',
            'Wrexham Maelor',
            'Wychavon',
            'Wycombe',
            'York'
            ]
    end

  def sub_region_options(region)
    region.subregions.map { |r| [r.code, r.code] }
  end

  def only_us_and_canada
    Carmen::Country.all.select { |c| %w(US CA).include?(c.code) }
end
end
